// This file is auto generated by the protocol-buffers compiler

/* eslint-disable quotes */
/* eslint-disable indent */
/* eslint-disable no-redeclare */
/* eslint-disable camelcase */

// Remember to `npm install --save protocol-buffers-encodings`
var encodings = require('protocol-buffers-encodings')
var varint = encodings.varint
var skip = encodings.skip

var Versions = exports.Versions = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

var Options = exports.Options = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

var Archive = exports.Archive = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

defineVersions()
defineOptions()
defineArchive()

function defineVersions () {
  var enc = [
    encodings.string
  ]

  Versions.encodingLength = encodingLength
  Versions.encode = encode
  Versions.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (defined(obj.v8)) {
      var len = enc[0].encodingLength(obj.v8)
      length += 1 + len
    }
    if (defined(obj.uv)) {
      var len = enc[0].encodingLength(obj.uv)
      length += 1 + len
    }
    if (defined(obj.node)) {
      var len = enc[0].encodingLength(obj.node)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (defined(obj.v8)) {
      buf[offset++] = 10
      enc[0].encode(obj.v8, buf, offset)
      offset += enc[0].encode.bytes
    }
    if (defined(obj.uv)) {
      buf[offset++] = 18
      enc[0].encode(obj.uv, buf, offset)
      offset += enc[0].encode.bytes
    }
    if (defined(obj.node)) {
      buf[offset++] = 26
      enc[0].encode(obj.node, buf, offset)
      offset += enc[0].encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      v8: "",
      uv: "",
      node: ""
    }
    while (true) {
      if (end <= offset) {
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.v8 = enc[0].decode(buf, offset)
        offset += enc[0].decode.bytes
        break
        case 2:
        obj.uv = enc[0].decode(buf, offset)
        offset += enc[0].decode.bytes
        break
        case 3:
        obj.node = enc[0].decode(buf, offset)
        offset += enc[0].decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defineOptions () {
  var enc = [
    encodings.string,
    encodings.bool
  ]

  Options.encodingLength = encodingLength
  Options.encode = encode
  Options.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (defined(obj.filename)) {
      var len = enc[0].encodingLength(obj.filename)
      length += 1 + len
    }
    if (defined(obj.optimized)) {
      var len = enc[1].encodingLength(obj.optimized)
      length += 1 + len
    }
    if (defined(obj.externals)) {
      for (var i = 0; i < obj.externals.length; i++) {
        if (!defined(obj.externals[i])) continue
        var len = enc[0].encodingLength(obj.externals[i])
        length += 1 + len
      }
    }
    if (defined(obj.assets)) {
      for (var i = 0; i < obj.assets.length; i++) {
        if (!defined(obj.assets[i])) continue
        var len = enc[0].encodingLength(obj.assets[i])
        length += 1 + len
      }
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (defined(obj.filename)) {
      buf[offset++] = 10
      enc[0].encode(obj.filename, buf, offset)
      offset += enc[0].encode.bytes
    }
    if (defined(obj.optimized)) {
      buf[offset++] = 16
      enc[1].encode(obj.optimized, buf, offset)
      offset += enc[1].encode.bytes
    }
    if (defined(obj.externals)) {
      for (var i = 0; i < obj.externals.length; i++) {
        if (!defined(obj.externals[i])) continue
        buf[offset++] = 26
        enc[0].encode(obj.externals[i], buf, offset)
        offset += enc[0].encode.bytes
      }
    }
    if (defined(obj.assets)) {
      for (var i = 0; i < obj.assets.length; i++) {
        if (!defined(obj.assets[i])) continue
        buf[offset++] = 34
        enc[0].encode(obj.assets[i], buf, offset)
        offset += enc[0].encode.bytes
      }
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      filename: "",
      optimized: false,
      externals: [],
      assets: []
    }
    while (true) {
      if (end <= offset) {
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.filename = enc[0].decode(buf, offset)
        offset += enc[0].decode.bytes
        break
        case 2:
        obj.optimized = enc[1].decode(buf, offset)
        offset += enc[1].decode.bytes
        break
        case 3:
        obj.externals.push(enc[0].decode(buf, offset))
        offset += enc[0].decode.bytes
        break
        case 4:
        obj.assets.push(enc[0].decode(buf, offset))
        offset += enc[0].decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defineArchive () {
  var Entry = Archive.Entry = {
    buffer: true,
    encodingLength: null,
    encode: null,
    decode: null
  }

  var Index = Archive.Index = {
    buffer: true,
    encodingLength: null,
    encode: null,
    decode: null
  }

  defineEntry()
  defineIndex()

  function defineEntry () {
    var enc = [
      encodings.varint,
      encodings.bytes
    ]

    Entry.encodingLength = encodingLength
    Entry.encode = encode
    Entry.decode = decode

    function encodingLength (obj) {
      var length = 0
      if (defined(obj.mode)) {
        var len = enc[0].encodingLength(obj.mode)
        length += 1 + len
      }
      if (defined(obj.size)) {
        var len = enc[0].encodingLength(obj.size)
        length += 1 + len
      }
      if (defined(obj.buffer)) {
        var len = enc[1].encodingLength(obj.buffer)
        length += 1 + len
      }
      return length
    }

    function encode (obj, buf, offset) {
      if (!offset) offset = 0
      if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
      var oldOffset = offset
      if (defined(obj.mode)) {
        buf[offset++] = 8
        enc[0].encode(obj.mode, buf, offset)
        offset += enc[0].encode.bytes
      }
      if (defined(obj.size)) {
        buf[offset++] = 16
        enc[0].encode(obj.size, buf, offset)
        offset += enc[0].encode.bytes
      }
      if (defined(obj.buffer)) {
        buf[offset++] = 26
        enc[1].encode(obj.buffer, buf, offset)
        offset += enc[1].encode.bytes
      }
      encode.bytes = offset - oldOffset
      return buf
    }

    function decode (buf, offset, end) {
      if (!offset) offset = 0
      if (!end) end = buf.length
      if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
      var oldOffset = offset
      var obj = {
        mode: 0,
        size: 0,
        buffer: null
      }
      while (true) {
        if (end <= offset) {
          decode.bytes = offset - oldOffset
          return obj
        }
        var prefix = varint.decode(buf, offset)
        offset += varint.decode.bytes
        var tag = prefix >> 3
        switch (tag) {
          case 1:
          obj.mode = enc[0].decode(buf, offset)
          offset += enc[0].decode.bytes
          break
          case 2:
          obj.size = enc[0].decode(buf, offset)
          offset += enc[0].decode.bytes
          break
          case 3:
          obj.buffer = enc[1].decode(buf, offset)
          offset += enc[1].decode.bytes
          break
          default:
          offset = skip(prefix & 7, buf, offset)
        }
      }
    }
  }

  function defineIndex () {
    var Entry = Index.Entry = {
      buffer: true,
      encodingLength: null,
      encode: null,
      decode: null
    }

    defineEntry()

    function defineEntry () {
      var enc = [
        encodings.varint,
        encodings.string
      ]

      Entry.encodingLength = encodingLength
      Entry.encode = encode
      Entry.decode = decode

      function encodingLength (obj) {
        var length = 0
        if (defined(obj.id)) {
          var len = enc[0].encodingLength(obj.id)
          length += 1 + len
        }
        if (defined(obj.filename)) {
          var len = enc[1].encodingLength(obj.filename)
          length += 1 + len
        }
        return length
      }

      function encode (obj, buf, offset) {
        if (!offset) offset = 0
        if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
        var oldOffset = offset
        if (defined(obj.id)) {
          buf[offset++] = 8
          enc[0].encode(obj.id, buf, offset)
          offset += enc[0].encode.bytes
        }
        if (defined(obj.filename)) {
          buf[offset++] = 18
          enc[1].encode(obj.filename, buf, offset)
          offset += enc[1].encode.bytes
        }
        encode.bytes = offset - oldOffset
        return buf
      }

      function decode (buf, offset, end) {
        if (!offset) offset = 0
        if (!end) end = buf.length
        if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
        var oldOffset = offset
        var obj = {
          id: 0,
          filename: ""
        }
        while (true) {
          if (end <= offset) {
            decode.bytes = offset - oldOffset
            return obj
          }
          var prefix = varint.decode(buf, offset)
          offset += varint.decode.bytes
          var tag = prefix >> 3
          switch (tag) {
            case 1:
            obj.id = enc[0].decode(buf, offset)
            offset += enc[0].decode.bytes
            break
            case 2:
            obj.filename = enc[1].decode(buf, offset)
            offset += enc[1].decode.bytes
            break
            default:
            offset = skip(prefix & 7, buf, offset)
          }
        }
      }
    }

    var enc = [
      encodings.varint,
      Entry
    ]

    Index.encodingLength = encodingLength
    Index.encode = encode
    Index.decode = decode

    function encodingLength (obj) {
      var length = 0
      if (defined(obj.size)) {
        var len = enc[0].encodingLength(obj.size)
        length += 1 + len
      }
      if (defined(obj.entries)) {
        for (var i = 0; i < obj.entries.length; i++) {
          if (!defined(obj.entries[i])) continue
          var len = enc[1].encodingLength(obj.entries[i])
          length += varint.encodingLength(len)
          length += 1 + len
        }
      }
      return length
    }

    function encode (obj, buf, offset) {
      if (!offset) offset = 0
      if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
      var oldOffset = offset
      if (defined(obj.size)) {
        buf[offset++] = 8
        enc[0].encode(obj.size, buf, offset)
        offset += enc[0].encode.bytes
      }
      if (defined(obj.entries)) {
        for (var i = 0; i < obj.entries.length; i++) {
          if (!defined(obj.entries[i])) continue
          buf[offset++] = 18
          varint.encode(enc[1].encodingLength(obj.entries[i]), buf, offset)
          offset += varint.encode.bytes
          enc[1].encode(obj.entries[i], buf, offset)
          offset += enc[1].encode.bytes
        }
      }
      encode.bytes = offset - oldOffset
      return buf
    }

    function decode (buf, offset, end) {
      if (!offset) offset = 0
      if (!end) end = buf.length
      if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
      var oldOffset = offset
      var obj = {
        size: 0,
        entries: []
      }
      while (true) {
        if (end <= offset) {
          decode.bytes = offset - oldOffset
          return obj
        }
        var prefix = varint.decode(buf, offset)
        offset += varint.decode.bytes
        var tag = prefix >> 3
        switch (tag) {
          case 1:
          obj.size = enc[0].decode(buf, offset)
          offset += enc[0].decode.bytes
          break
          case 2:
          var len = varint.decode(buf, offset)
          offset += varint.decode.bytes
          obj.entries.push(enc[1].decode(buf, offset, offset + len))
          offset += enc[1].decode.bytes
          break
          default:
          offset = skip(prefix & 7, buf, offset)
        }
      }
    }
  }

  var enc = [
    Index
  ]

  Archive.encodingLength = encodingLength
  Archive.encode = encode
  Archive.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (defined(obj.index)) {
      var len = enc[0].encodingLength(obj.index)
      length += varint.encodingLength(len)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (defined(obj.index)) {
      buf[offset++] = 10
      varint.encode(enc[0].encodingLength(obj.index), buf, offset)
      offset += varint.encode.bytes
      enc[0].encode(obj.index, buf, offset)
      offset += enc[0].encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      index: null
    }
    while (true) {
      if (end <= offset) {
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        var len = varint.decode(buf, offset)
        offset += varint.decode.bytes
        obj.index = enc[0].decode(buf, offset, offset + len)
        offset += enc[0].decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defined (val) {
  return val !== null && val !== undefined && (typeof val !== 'number' || !isNaN(val))
}
